# SPDX-FileCopyrightText: 2026 The MCUScript Contributors
# SPDX-License-Identifier: Apache-2.0
"""The second backend: a container, lowered to plain C.

Every program has two lowerings and must have both (spec/README.md).
This is the other one, and the promise is that they produce identical
results — not that they look alike.

**It consumes the container, not an earlier intermediate form.** Both
backends therefore start from the same bytes: a divergence cannot be
blamed on two different inputs, and a container that arrived over the
air can still be compiled in. It also means this backend inherits the
verifier's work — the types, the depths and the branch targets are
already proved, so nothing here has to check them.

**The lowering is the stack machine, not a reconstructed expression
tree.** Each operand-stack position becomes a pair of C variables and
each branch becomes a forward ``goto``, which the no-backward-jumps rule
makes legal by construction. The result reads like a machine and
compiles like one: any optimizing compiler puts those variables in
registers and the redundant copies vanish. Reconstructing `a + b * c`
would produce prettier C and one more chance to be wrong, and prettier
C was never the requirement.

**Linking is the C linker's.** Each import becomes an `extern` function
the embedder implements. There is no import table and no name resolution
at run time, because for a compiled-in program the embedder's registry
is known at build time — so a script referring to something that is not
there is a link error, at the moment the firmware is built, which is
strictly earlier than the load-time refusal the VM would give.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from .container import Container, Function, ImportKind
from .opcodes import BY_CODE, Operand, ValType
from .verify import stack_shapes

_C_TYPE = {
    ValType.I32: "i32",
    ValType.BOOL: "boolean",
    ValType.I64: "i64",
    ValType.F32: "f32",
}


class UnsupportedProgram(Exception):
    """The container uses something this backend cannot lower yet."""


def mangle(name: str) -> str:
    """A C identifier from an entity name.

    Anything that is not a C identifier character becomes an underscore,
    which can collide — `fan.speed` and `fan_speed` both become
    `fan_speed`. The generator refuses rather than emitting two
    declarations of one symbol and letting the C compiler explain it.
    """
    return re.sub(r"[^A-Za-z0-9_]", "_", name)


@dataclass(frozen=True, slots=True)
class Symbols:
    """The extern functions a generated translation unit expects."""

    reads: tuple[tuple[str, str], ...]  # (entity name, C symbol)
    writes: tuple[tuple[str, str], ...]
    calls: tuple[tuple[str, str], ...]
    entries: tuple[tuple[str, str], ...]


def symbols(container: Container) -> Symbols:
    reads, writes, calls, entries = [], [], [], []
    seen: dict[str, str] = {}

    def claim(prefix: str, name: str) -> str:
        symbol = f"mcuscript_{prefix}__{mangle(name)}"
        if symbol in seen and seen[symbol] != name:
            raise UnsupportedProgram(
                f"'{name}' and '{seen[symbol]}' both mangle to {symbol}"
            )
        seen[symbol] = name
        return symbol

    for imp in container.imports:
        if imp.kind == ImportKind.FUNCTION:
            calls.append((imp.name, claim("call", imp.name)))
            continue
        if imp.access & 0x01:
            reads.append((imp.name, claim("read", imp.name)))
        if imp.access & 0x02:
            writes.append((imp.name, claim("write", imp.name)))
    for fn in container.functions:
        if fn.invocable:
            entries.append((fn.name, claim("entry", fn.name)))
    return Symbols(tuple(reads), tuple(writes), tuple(calls), tuple(entries))


def generate(container: Container, *, source: str = "a container") -> str:
    """Lower a verified container to one C translation unit."""
    if len(container.functions) != sum(1 for f in container.functions if f.invocable):
        raise UnsupportedProgram("the call group is not lowered yet")

    names = symbols(container)
    shapes = stack_shapes(container)
    out: list[str] = []
    w = out.append

    w(f"/* Generated by mcuscript from {source}. Do not edit. */")
    w("")
    w("#include <stdbool.h>")
    w("#include <stdint.h>")
    w("")
    w('#include "mcuscript.h"')
    w('#include "mcuscript_ops.h"')
    w("")
    w("/* Two roundings, never a fused multiply-add: the specification")
    w(" * pins the arithmetic and the build must honour it (spec §1.5).")
    w(" *")
    w(" * GCC does not implement this pragma — it warns that the pragma is")
    w(" * ignored and then contracts anyway — so a GCC build must pass")
    w(" * -ffp-contract=off. The pragma is emitted where it is honoured")
    w(" * rather than everywhere, because a warning nobody can act on")
    w(" * trains people to ignore warnings. */")
    w("#if defined(__clang__) || !defined(__GNUC__)")
    w("#pragma STDC FP_CONTRACT OFF")
    w("#endif")
    w("")

    for name, symbol in names.reads:
        w(f"/* {name} */")
        w(f"extern mcuscript_value {symbol}(void);")
    for name, symbol in names.writes:
        w(f"/* {name} */")
        w(f"extern void {symbol}(mcuscript_value value);")
    for name, symbol in names.calls:
        w(f"/* {name} */")
        w(f"extern bool {symbol}(const mcuscript_value *arguments,")
        w(f"{' ' * (len(symbol) + 12)}mcuscript_value *result);")
    if names.reads or names.writes or names.calls:
        w("")

    entry_symbol = dict(names.entries)
    for fn in container.functions:
        out.extend(_function(container, fn, shapes[fn.name], entry_symbol[fn.name]))
        w("")
    return "\n".join(out).rstrip() + "\n"


def header(container: Container, *, source: str = "a container") -> str:
    """The declarations an embedder needs to call the generated code."""
    names = symbols(container)
    out = [
        f"/* Generated by mcuscript from {source}. Do not edit. */",
        "",
        "#ifndef MCUSCRIPT_GENERATED_H",
        "#define MCUSCRIPT_GENERATED_H",
        "",
        '#include "mcuscript.h"',
        "",
    ]
    for fn in container.functions:
        if not fn.invocable:
            continue
        symbol = dict(names.entries)[fn.name]
        out.append(f"/* {fn.name} */")
        out.append(f"bool {symbol}(mcuscript_value *result, mcuscript_fault *fault);")
    out += ["", "#endif /* MCUSCRIPT_GENERATED_H */"]
    return "\n".join(out) + "\n"


# -- one function ---------------------------------------------------------


def _slot(depth: int) -> tuple[str, str]:
    return f"v{depth}", f"s{depth}"


def _local(index: int) -> tuple[str, str]:
    return f"l{index}", f"m{index}"


def _read_slot(name: str, type_: ValType) -> str:
    """A slot, as the C value of its verified type."""
    if type_ is ValType.I32:
        return f"mcuscript_op_as_i32({name})"
    if type_ is ValType.BOOL:
        return f"({name} != 0)"
    raise UnsupportedProgram(f"{type_} is not lowered yet")


def _write_slot(name: str, type_: ValType, expression: str) -> str:
    if type_ is ValType.I32:
        return f"{name} = mcuscript_op_from_i32({expression});"
    if type_ is ValType.BOOL:
        return f"{name} = ({expression}) ? 1u : 0u;"
    raise UnsupportedProgram(f"{type_} is not lowered yet")


_BINARY = {
    "add.i32": "mcuscript_op_add_i32({a}, {b})",
    "sub.i32": "mcuscript_op_sub_i32({a}, {b})",
    "mul.i32": "mcuscript_op_mul_i32({a}, {b})",
}

_COMPARE = {
    "eq.i32": "==",
    "ne.i32": "!=",
    "lt.i32": "<",
    "le.i32": "<=",
    "gt.i32": ">",
    "ge.i32": ">=",
}


def _function(
    container: Container, fn: Function, shapes: dict, symbol: str
) -> list[str]:
    start = fn.code_offset
    end = start + _region_length(container, fn)
    code = container.code
    targets = _branch_targets(code, start, end)

    body: list[str] = []
    pc = start
    while pc < end:
        op = BY_CODE[code[pc]]
        stack = shapes[pc]
        if pc in targets:
            body.append(f"{targets[pc]}:")
        body.extend(
            "\t" + line
            for line in _instruction(container, fn, op, code, pc, stack, targets)
        )
        pc += op.size

    lines = [
        f"bool {symbol}(mcuscript_value *result, mcuscript_fault *fault)",
        "{",
    ]
    for i, type_ in enumerate(fn.local_types):
        value, state = _local(i)
        lines.append(f"\t/* local {i}: {type_} */")
        lines.append(f"\tuint64_t {value} = 0;")
        lines.append(f"\tuint8_t {state} = MCUSCRIPT_UNAVAILABLE;")
    for i in range(fn.max_stack):
        value, state = _slot(i)
        lines.append(f"\tuint64_t {value} = 0;")
        lines.append(f"\tuint8_t {state} = MCUSCRIPT_VALID;")
    # Both are unused in a program with no branch, no host call and no
    # return value; casting them away unconditionally is cheaper than
    # working out which.
    lines.append("\t(void)result;")
    lines.append("\t(void)fault;")
    lines.append("")
    lines.extend(body)
    lines.append("}")
    return lines


def _region_length(container: Container, fn: Function) -> int:
    end = len(container.code)
    for other in container.functions:
        if fn.code_offset < other.code_offset < end:
            end = other.code_offset
    return end - fn.code_offset


def _branch_targets(code: bytes, start: int, end: int) -> dict[int, str]:
    targets = []
    pc = start
    while pc < end:
        op = BY_CODE[code[pc]]
        if op.is_branch:
            delta = int.from_bytes(code[pc + 1 : pc + 3], "little", signed=True)
            targets.append(pc + op.size + delta)
        pc += op.size
    return {t: f"L{t - start}" for t in sorted(set(targets))}


def _instruction(
    container: Container,
    fn: Function,
    op,
    code: bytes,
    pc: int,
    stack: tuple[ValType, ...],
    targets: dict[int, str],
) -> list[str]:
    depth = len(stack)
    top, top_state = _slot(depth - 1) if depth else ("", "")
    push, push_state = _slot(depth)
    index = code[pc + 1] if op.operand is not Operand.NONE else 0
    name = op.name

    if name == "const.i32.s8":
        literal = int.from_bytes(code[pc + 1 : pc + 2], "little", signed=True)
        return [
            _write_slot(push, ValType.I32, str(literal)),
            f"{push_state} = MCUSCRIPT_VALID;",
        ]
    if name == "const.i32.s16":
        literal = int.from_bytes(code[pc + 1 : pc + 3], "little", signed=True)
        return [
            _write_slot(push, ValType.I32, str(literal)),
            f"{push_state} = MCUSCRIPT_VALID;",
        ]
    if name == "const.i32":
        literal = container.constants[index].value
        return [
            _write_slot(push, ValType.I32, _c_i32(literal)),
            f"{push_state} = MCUSCRIPT_VALID;",
        ]
    if name in ("const.true", "const.false"):
        return [
            f"{push} = {1 if name.endswith('true') else 0}u;",
            f"{push_state} = MCUSCRIPT_VALID;",
        ]

    if name == "load.l":
        value, state = _local(index)
        return [f"{push} = {value};", f"{push_state} = {state};"]
    if name == "store.l":
        value, state = _local(index)
        return [f"{value} = {top};", f"{state} = {top_state};"]

    if name == "load.h":
        imp = container.imports[index]
        symbol = f"mcuscript_read__{mangle(imp.name)}"
        return [
            "{",
            f"\tmcuscript_value read = {symbol}();",
            "\t" + _write_slot(push, imp.type, f"read.as.{_C_TYPE[imp.type]}"),
            f"\t{push_state} = read.validity;",
            "}",
        ]
    if name == "store.h":
        imp = container.imports[index]
        symbol = f"mcuscript_write__{mangle(imp.name)}"
        return [
            "{",
            "\tmcuscript_value written;",
            "\twritten.as.i64 = 0;",
            f"\twritten.as.{_C_TYPE[imp.type]} = {_read_slot(top, imp.type)};",
            f"\twritten.validity = {top_state};",
            f"\t{symbol}(written);",
            "}",
        ]
    if name == "call.h":
        imp = container.imports[index]
        symbol = f"mcuscript_call__{mangle(imp.name)}"
        base = depth - len(imp.param_types)
        lines = ["{"]
        if imp.param_types:
            lines.append(f"\tmcuscript_value arguments[{len(imp.param_types)}];")
        for p, type_ in enumerate(imp.param_types):
            value, state = _slot(base + p)
            lines.append(f"\targuments[{p}].as.i64 = 0;")
            lines.append(
                f"\targuments[{p}].as.{_C_TYPE[type_]} = {_read_slot(value, type_)};"
            )
            lines.append(f"\targuments[{p}].validity = {state};")
        lines.append("\tmcuscript_value produced;")
        lines.append("\tproduced.as.i64 = 0;")
        lines.append("\tproduced.validity = MCUSCRIPT_UNAVAILABLE;")
        argument_list = "arguments" if imp.param_types else "NULL"
        lines.append(f"\tif (!{symbol}({argument_list}, &produced)) {{")
        lines.append("\t\tif (fault != NULL)")
        lines.append("\t\t\t*fault = MCUSCRIPT_HOST_FAULT;")
        lines.append("\t\treturn false;")
        lines.append("\t}")
        if imp.type is not ValType.VOID:
            value, state = _slot(base)
            lines.append(
                "\t" + _write_slot(value, imp.type, f"produced.as.{_C_TYPE[imp.type]}")
            )
            lines.append(f"\t{state} = produced.validity;")
        lines.append("}")
        return lines

    if name == "drop":
        # Nothing to emit: the slot simply stops being read. The C
        # compiler removes the dead store the producer made.
        return [f"/* drop {top} */"]
    if name == "dup":
        return [f"{push} = {top};", f"{push_state} = {top_state};"]

    if name in _BINARY:
        a, a_state = _slot(depth - 2)
        b, b_state = _slot(depth - 1)
        expression = _BINARY[name].format(
            a=_read_slot(a, ValType.I32), b=_read_slot(b, ValType.I32)
        )
        return [
            _write_slot(a, ValType.I32, expression),
            f"{a_state} = mcuscript_op_worse({a_state}, {b_state});",
        ]
    if name in ("div.i32", "rem.i32"):
        a, a_state = _slot(depth - 2)
        b, b_state = _slot(depth - 1)
        helper = "mcuscript_op_div_i32" if name == "div.i32" else "mcuscript_op_rem_i32"
        return [
            f"{a_state} = mcuscript_op_worse({a_state}, {b_state});",
            _write_slot(
                a,
                ValType.I32,
                f"{helper}({_read_slot(a, ValType.I32)}, "
                f"{_read_slot(b, ValType.I32)}, &{a_state})",
            ),
        ]
    if name == "neg.i32":
        return [
            _write_slot(
                top,
                ValType.I32,
                f"mcuscript_op_neg_i32({_read_slot(top, ValType.I32)})",
            )
        ]
    if name in _COMPARE:
        a, a_state = _slot(depth - 2)
        b, b_state = _slot(depth - 1)
        expression = (
            f"{_read_slot(a, ValType.I32)} {_COMPARE[name]} "
            f"{_read_slot(b, ValType.I32)}"
        )
        return [
            _write_slot(a, ValType.BOOL, expression),
            f"{a_state} = mcuscript_op_worse({a_state}, {b_state});",
        ]
    if name == "not":
        return [f"{top} = {top} ? 0u : 1u;"]

    if name == "else":
        value, state = _slot(depth - 2)
        fallback, fallback_state = _slot(depth - 1)
        return [
            f"if ({state} != MCUSCRIPT_VALID) {{",
            f"\t{value} = {fallback};",
            f"\t{state} = {fallback_state};",
            "}",
        ]
    if name in ("is_valid", "is_unavailable", "is_invalid"):
        wanted = {
            "is_valid": "MCUSCRIPT_VALID",
            "is_unavailable": "MCUSCRIPT_UNAVAILABLE",
            "is_invalid": "MCUSCRIPT_INVALID",
        }[name]
        return [
            f"{top} = ({top_state} == {wanted}) ? 1u : 0u;",
            f"{top_state} = MCUSCRIPT_VALID;",
        ]

    if name == "jmp":
        delta = int.from_bytes(code[pc + 1 : pc + 3], "little", signed=True)
        return [f"goto {targets[pc + op.size + delta]};"]
    if name in ("jmp_if_false", "jmp_if_true"):
        delta = int.from_bytes(code[pc + 1 : pc + 3], "little", signed=True)
        label = targets[pc + op.size + delta]
        test = f"{top} == 0" if name == "jmp_if_false" else f"{top} != 0"
        return [
            # An absent reading must not become a wrong action (§1.3.1).
            f"if ({top_state} != MCUSCRIPT_VALID) {{",
            "\tif (fault != NULL)",
            "\t\t*fault = MCUSCRIPT_ABSENT_CONDITION;",
            "\treturn false;",
            "}",
            f"if ({test})",
            f"\tgoto {label};",
        ]

    if name == "ret":
        return ["return true;"]
    if name == "ret_v":
        return [
            "if (result != NULL) {",
            "\tresult->as.i64 = 0;",
            f"\tresult->as.{_C_TYPE[fn.return_type]} = "
            f"{_read_slot(top, fn.return_type)};",
            f"\tresult->validity = {top_state};",
            "}",
            "return true;",
        ]

    raise UnsupportedProgram(f"{name} is not lowered yet")


def _c_i32(value: int) -> str:
    # INT32_MIN has no negative literal in C: -2147483648 is unary minus
    # applied to a constant that does not fit an int.
    if value == -(2**31):
        return "INT32_MIN"
    return str(value)
