# SPDX-FileCopyrightText: 2026 The MCUScript Contributors
# SPDX-License-Identifier: Apache-2.0
"""The embedder's import table, written out as C — §7.5.

A registry is a document the compiler reads (§7.3) and the same table
has to exist a second time on the device, as the `mcuscript_import[]`
a loader resolves against (§4.5). Two copies of one table is exactly
the arrangement this project distrusts, and here the second copy is the
dangerous one: §4.4 carries an entity's dimension into the container and
checks it at load, but a **parameter's** dimension is never carried and
never checked, so a host whose table says milliseconds where the
registry said seconds is wrong at run time and quiet about it.

So the second copy is generated rather than written. What the header
holds is an index enum and the array; everything around it — the
callbacks, the `mcuscript_host` itself — stays the embedder's, and a
header included twice or a name that moved is something the C compiler
says out loud.
"""

from __future__ import annotations

from pathlib import Path

from .opcodes import ValType
from .registry import Entity, HostFunction, Registry

_TYPE = {
    ValType.VOID: "MCUSCRIPT_VOID",
    ValType.I32: "MCUSCRIPT_I32",
    ValType.I64: "MCUSCRIPT_I64",
    ValType.F32: "MCUSCRIPT_F32",
    ValType.BOOL: "MCUSCRIPT_BOOL",
}

_ACCESS = {
    (True, False): "MCUSCRIPT_ACCESS_READ",
    (False, True): "MCUSCRIPT_ACCESS_WRITE",
    (True, True): "MCUSCRIPT_ACCESS_BOTH",
}


class NameCollision(Exception):
    """Two registry names that C cannot tell apart."""


def _symbol(name: str) -> str:
    return name.upper().replace(".", "_")


def _lower(name: str) -> str:
    return name.lower().replace(".", "_")


def guard(path: Path) -> str:
    """A header guard from the file's own name, so two headers can coexist."""
    word = "".join(char if char.isalnum() else "_" for char in path.name).upper()
    return f"MCUSCRIPT_{word}"


def generate(registry: Registry, path: Path, *, source: str = "a registry") -> str:
    """The header, as text. `path` is only read for the guard's name."""
    entries: list[Entity | HostFunction] = [*registry.entities, *registry.functions]
    _distinct(entries)
    sentry = guard(path)

    out = [
        f"/* Generated by mcuscript from {source}. Do not edit. */",
        "",
        "/*",
        " * The host's import table (spec §4.5): everything a script may",
        " * reach, in the order the loader indexes it. The read, write and",
        " * invoke callbacks are given this index and nothing else.",
        " *",
        " * Include this in exactly one translation unit. The array is",
        " * `static const`, so a second copy is a second copy.",
        " */",
        "",
        f"#ifndef {sentry}",
        f"#define {sentry}",
        "",
        '#include "mcuscript.h"',
        "",
        "enum {",
    ]
    for index, entry in enumerate(entries):
        out.append(f"\tMCUSCRIPT_IMPORT_{_symbol(entry.name)} = {index},")
    out.append(f"\tMCUSCRIPT_IMPORT_COUNT = {len(entries)}")
    out.append("};")
    out.append("")

    for function in registry.functions:
        if not function.params:
            continue
        types = ", ".join(_TYPE[p.type] for p in function.params)
        out.append(
            f"static const uint8_t mcuscript_params_{_lower(function.name)}[] "
            f"= {{ {types} }};"
        )
    if any(f.params for f in registry.functions):
        out.append("")

    out.append("static const mcuscript_import mcuscript_imports[] = {")
    for entry in entries:
        out.append("\t" + _record(entry))
    out.append("};")
    out += ["", f"#endif /* {sentry} */"]
    return "\n".join(out) + "\n"


def _record(entry: Entity | HostFunction) -> str:
    if isinstance(entry, Entity):
        quantity = entry.quantity
        kind, access = (
            "MCUSCRIPT_KIND_ENTITY",
            _ACCESS[(entry.readable, entry.writable)],
        )
        params, count = "NULL", 0
    else:
        quantity = entry.returns
        kind, access = "MCUSCRIPT_KIND_FUNCTION", "MCUSCRIPT_ACCESS_NONE"
        count = len(entry.params)
        params = f"mcuscript_params_{_lower(entry.name)}" if count else "NULL"
    type_ = _TYPE[quantity.type] if quantity is not None else _TYPE[ValType.VOID]
    dimension = quantity.dimension.id if quantity and quantity.dimension else 0
    return (
        f'{{ "{entry.name}", {kind}, {access}, {type_}, '
        f"{dimension}, {count}, {params} }},"
    )


def _distinct(entries: list[Entity | HostFunction]) -> None:
    """`fan.on` and `fan_on` are two names and one C identifier."""
    #: The one name the enum needs for itself.
    seen: dict[str, str] = {"COUNT": "the table's own length"}
    for entry in entries:
        symbol = _symbol(entry.name)
        if symbol in seen:
            raise NameCollision(
                f"`{entry.name}` and `{seen[symbol]}` both become "
                f"MCUSCRIPT_IMPORT_{symbol} — rename one"
            )
        seen[symbol] = entry.name


def write(registry: Registry, path: Path, *, source: str = "a registry") -> None:
    """Generate or overwrite the header. Nothing else in the tree is touched."""
    path.write_text(generate(registry, path, source=source), encoding="utf-8")
